name: Build and Push captaind Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: captaind
      TAG: ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build captaind binary
        run: |
          cargo build --release --bin captaind
          cp target/release/captaind ./captaind-linux-x86_64
      - name: Docker build and push
        if: github.actor != 'dependabot[bot]'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGENAME }}
          registry: ${{ env.REGISTRY }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile.captaind
